(ns qbits.alia.embedded.config
  (:require [clj-yaml.core :as yaml]))

(def config-template
  "Template for a cassandra configuration"
  {:concurrent_writes                               32,
   :hinted_handoff_enabled                          false,
   :dynamic_snitch_update_interval_in_ms            100,
   :max_hint_window_in_ms                           10800000,
   :cross_node_timeout                              false,
   :unlogged_batch_across_partitions_warn_threshold 10,
   :compaction_throughput_mb_per_sec                16,
   :storage_port                                    7000,
   :start_native_transport                          true,
   :snapshot_before_compaction                      false,
   :permissions_validity_in_ms                      2000,
   :compaction_large_partition_warning_threshold_mb 100,
   :max_hints_delivery_threads                      2,
   :gc_warn_threshold_in_ms                         1000,
   :commit_failure_policy                           "stop",
   :truncate_request_timeout_in_ms                  60000,
   :request_timeout_in_ms                           10000,
   :concurrent_counter_writes                       32,
   :range_request_timeout_in_ms                     10000,
   :trickle_fsync_interval_in_kb                    10240,
   :endpoint_snitch                                 "SimpleSnitch",
   :role_manager                                    "CassandraRoleManager",
   :ssl_storage_port                                7001,
   :tracetype_repair_ttl                            604800,
   :hints_flush_period_in_ms                        10000,
   :counter_cache_save_period                       0,
   :batch_size_fail_threshold_in_kb                 50,
   :row_cache_size_in_mb                            0,
   :tombstone_warn_threshold                        1000,
   :concurrent_materialized_view_writes             32,
   :rpc_port                                        9160,
   :incremental_backups                             false,
   :commitlog_segment_size_in_mb                    32,
   :tracetype_query_ttl                             86400,
   :key_cache_save_period                           0,
   :read_request_timeout_in_ms                      5000,
   :rpc_server_type                                 "sync",
   :dynamic_snitch_reset_interval_in_ms             600000,
   :seed_provider
   [{:class_name "org.apache.cassandra.locator.SimpleSeedProvider",
      :parameters [{:seeds "127.0.0.1"}]}],
   :counter_cache_size_in_mb                        nil,
   :disk_failure_policy                             "stop",
   :listen_address                                  "localhost",
   :memtable_allocation_type                        "heap_buffers",
   :tombstone_failure_threshold                     100000,
   :native_transport_port                           9042,
   :index_summary_capacity_in_mb                    nil,
   :commitlog_sync                                  "periodic",
   :enable_scripted_user_defined_functions          false,
   :max_hints_file_size_in_mb                       128,
   :rpc_keepalive                                   true,
   :trickle_fsync                                   false,
   :roles_validity_in_ms                            2000,
   :client_encryption_options
   {:enabled           false,
    :optional          false,
    :keystore          "conf/.keystore",
    :keystore_password "cassandra"},
   :key_cache_size_in_mb                            nil,
   :commitlog_sync_period_in_ms                     10000,
   :batch_size_warn_threshold_in_kb                 5,
   :row_cache_save_period                           0,
   :start_rpc                                       false,
   :rpc_address                                     "localhost",
   :cluster_name                                    "some-cluster-name",
   :inter_dc_tcp_nodelay                            false,
   :num_tokens                                      8,
   :thrift_framed_transport_size_in_mb              15,
   :partitioner                                     "org.apache.cassandra.dht.Murmur3Partitioner",
   :column_index_size_in_kb                         64,
   :internode_compression                           "all",
   :enable_user_defined_functions                   false,
   :dynamic_snitch_badness_threshold                0.1,
   :authorizer                                      "AllowAllAuthorizer",
   :batchlog_replay_throttle_in_kb                  1024,
   :hinted_handoff_throttle_in_kb                   1024,
   :cas_contention_timeout_in_ms                    1000,
   :counter_write_request_timeout_in_ms             5000,
   :windows_timer_interval                          1,
   :auto_snapshot                                   false,
   :write_request_timeout_in_ms                     2000,
   :request_scheduler                               "org.apache.cassandra.scheduler.NoScheduler",
   :concurrent_reads                                32,
   :authenticator                                   "AllowAllAuthenticator",
   :sstable_preemptive_open_interval_in_mb          50,
   :index_summary_resize_interval_in_minutes        60,
   :server_encryption_options
   {:internode_encryption "none",
    :keystore             "conf/.keystore",
    :keystore_password    "cassandra",
    :truststore           "conf/.truststore",
    :truststore_password  "cassandra"}})

(defn yaml-config
  [port storage-port]
  (-> config-template
      (assoc :native_transport_port port)
      (assoc :storage_port storage-port)
      (assoc :cluster_name (name (gensym "embedded-cassandra-")))
      (yaml/generate-string)))
